name: Build and Release PyroTracker

# Run this workflow when a Release is published on GitHub
on:
  release:
    types: [published]

# Permissions needed for the workflow to create releases and upload assets
permissions:
  contents: write

jobs:
  build-release:
    name: Build on ${{ matrix.os }}
    # Run on different operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Define the operating systems and corresponding Python versions
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Use a Python version compatible with your code (e.g., 3.9 based on README)
        python-version: ['3.9']

    steps:
    - name: Check out repository code
      # Action to get your code from the repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      # Action to install the specified Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compile Qt Resources
      run: |
        pyside6-rcc resources.qrc -o resources_rc.py
        # Verify the file was created (optional, for debugging CI)
        ls -l resources_rc.py

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=PyroTracker.ico --name=PyroTracker --add-data "PyroTracker.ico:." main.py

    - name: Prepare Artifact Name (Windows)
      if: runner.os == 'Windows' 
      run: |
        ren dist\PyroTracker.exe PyroTracker-windows.exe
        echo "ASSET_PATH=dist/PyroTracker-windows.exe" >> $env:GITHUB_ENV
        echo "ASSET_NAME=PyroTracker-windows.exe" >> $env:GITHUB_ENV
      shell: pwsh # Use PowerShell for Windows steps

    - name: Prepare Artifact Name (Linux)
      if: runner.os == 'Linux'
      run: |
        mv dist/PyroTracker dist/PyroTracker-linux
        echo "ASSET_PATH=dist/PyroTracker-linux" >> $GITHUB_ENV
        echo "ASSET_NAME=PyroTracker-linux" >> $GITHUB_ENV

    - name: Prepare Artifact Name (macOS)
      if: runner.os == 'macOS'
      run: |
        # macOS apps are bundles (folders). Zip it for easier distribution.
        zip -r dist/PyroTracker-macos.zip dist/PyroTracker.app
        echo "ASSET_PATH=dist/PyroTracker-macos.zip" >> $GITHUB_ENV
        echo "ASSET_NAME=PyroTracker-macos.zip" >> $GITHUB_ENV

    - name: Upload Release Asset
      # Action to upload the built file to the GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Get the upload URL from the trigger event (the release creation)
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.ASSET_PATH }}
        asset_name: ${{ env.ASSET_NAME }}
        asset_content_type: application/octet-stream # Generic binary type

    - name: Upload User Manual PDF
      # Run this step only on the Linux runner to avoid uploading the PDF multiple times
      if: runner.os == 'Linux'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Get upload URL from the release event that triggered the workflow
        upload_url: ${{ github.event.release.upload_url }}
        # Path to the PDF file in the repository (use ./ if it's in the root)
        asset_path: ./PyroTracker_manual.pdf
        # Name the asset should have in the release
        asset_name: PyroTracker_manual.pdf
        # Content type for PDF
        asset_content_type: application/pdf        
        